# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: moel-mal <moel-mal@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2019/10/22 23:45:41 by moel-mal          #+#    #+#              #
#    Updated: 2020/10/21 18:29:21 by moel-mal         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = libft.a

FLAGS = -Wall -Wextra -Werror -c

SRCS = ft_isalnum.c	ft_isprint.c ft_strcpy.c	ft_memcmp.c	ft_putchar_fd.c	ft_split.c	ft_strlcat.c	ft_strncmp.c	ft_substr.c ft_atoi.c	ft_isalpha.c	ft_itoa.c	ft_memcpy.c	ft_putendl_fd.c	ft_strchr.c	ft_strlcpy.c	ft_strnstr.c	ft_tolower.c ft_bzero.c	ft_isascii.c	ft_memccpy.c	ft_memmove.c	ft_putnbr_fd.c	ft_strdup.c	ft_strlen.c	ft_strrchr.c ft_toupper.c ft_calloc.c ft_isdigit.c ft_memchr.c	ft_memset.c	ft_putstr_fd.c	ft_strjoin.c	ft_strmapi.c	ft_strtrim.c

$(NAME): all

all:
	gcc $(FLAGS) $(SRCS)
	ar -rc $(NAME) *.o
	ranlib $(NAME)

clean:
	rm -f *.o

fclean: clean
	rm -f $(NAME)

re: fclean
	make all
